(defun simple-test (port string)
  (let* ((socket (usocket:socket-connect #(127 0 0 1) port))
	 (stream (usocket:socket-stream socket)))
    (write-line string stream)
    (force-output stream)
    (let ((result (read-line stream)))
      (close stream)
      (usocket:socket-close socket)
      result)))
